name: Automatic Release
run-name: ${{ github.actor }} is automatically releasing 🚀

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Generate token'
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.RELEASE_SECRET }}

      - name: 'Checking out code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: 'Setting up Node'
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ctype, iconv
          coverage: none

      - name: 'Installing Composer dependencies'
        run: composer install --no-progress --prefer-dist

      - name: 'Installing dependencies'
        run: npm ci

      - name: 'audit fix'
        run: npm audit fix
      - name: 'Verifying the signatures'
        run: npm audit signatures

      - name: 'Releasing via Semantic Release'
        run: npx semantic-release@21
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}