# File: .github/workflows/template-sync.yml

on:
  # cronjob trigger
  schedule:
    - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.RELEASE_SECRET }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # submodules: true

          token: ${{ secrets.PAT_SYNC_TOKEN }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          source_repo_path: VilnaCRM-Org/php-service-template
          upstream_branch: main
          pr_labels: template_sync